### ISSUE TITLE
Relation to upstream?

### ISSUE THREAD

**Issue by cstrahan** [probonopd/zsync-curl#11]
Hello, I was just curious what you had in mind for this fork; do you intend to push this upstream?

I discovered zsync-curl (and this fork) after stumbling across AppImage. zsync (and zsync-curl) both look rather nice, and I figured I would package zsync-curl for NixOS, but I'm not positive which source I should use, as upstream hasn't been updated in quite a while, though I get the feeling (from perusing the commits) that this fork is still a little bit of a work in progress.

Either way, very interesting work here and with AppImage :).

**Comment by probonopd** [comment]
Right now I'd consider this a "feature branch"; eventually we should do a pull request to upstream (or rename it). Did you contact the project on Launchpad?
