### ISSUE TITLE
don't bundle zlib

### ISSUE THREAD

**Issue by jsilhan** [probonopd/zsync-curl#12]
Hi,
do you plan to get rid of zlib bundling in your fork? This is the issue [blocking zlib to get into Fedora](https://bugzilla.redhat.com/show_bug.cgi?id=478617) as it can bring a security problem.

**Comment by probonopd** [comment]
Since I do not plan getting probonopd/zsync-curl into Fedora it is not an issue for me. I am working on this for use in the updater component of [AppImage](http://appimage.org).
