### ISSUE TITLE
Save tempfiles to destination directory when -o flag is set

### ISSUE THREAD

**Issue by ajwipf** [probonopd/zsync-curl#29]
I received the following error after setting `-o` to a different disk/partition from my working directory.
```
Target /partitionA/path/to/file.ext
rename: Invalid cross-device link
rename: Invalid cross-device link
```
exit code 1

The obvious solution was to `cd` into the destination directory (and by definition disk/partition) and run the command from there. Ideally temp files should be saved in the destination directory when the `-o` flag is set to avoid attempting to change links between partitions (you're gonna have a bad time).

**Comment by TheAssassin** [comment]
Can you please provide some more information on your system? What distro are you running?

Side note: I am going to rewrite zsync_curl completely soon (at least the "frontend"). I am not sure whether it's worth fixing that bug before. Is it critical for you, or does it have lesser priority?

**Comment by ajwipf** [comment]
Very low priority here since it's such a simple workaround. From my perspective, it's probably not worth fixing if the new frontend will have the correct behavior.

System info:
```
$ cat /etc/centos-release
CentOS Linux release 7.2.1511 (Core)
$ uname -r
3.10.0-327.36.1.el7.x86_64
```
Let me know if there's another system attribute you're curious about.

**Comment by wendal** [comment]
yes, it happen in my centos too.

**Comment by TheAssassin** [comment]
Please switch to [zsync2](https://github.com/TheAssassin/zsync2), and report bugs there if you find some. Closing as this repository is no longer developed.
