### ISSUE TITLE
Zsync fails to download package

### ISSUE THREAD

**Issue by maltesh** [probonopd/zsync-curl#32]
We have package download triggered via celery task,Given connectivity is poor(32 kB) and package size range from 1-5gb. Celery task limit is configured for 4 hours,we have seen download is getting freezed and zsync-curl is seen in orphan state.

Any info on why it fails to download is useful ?

**Comment by TheAssassin** [comment]
There's a zillion reasons that could cause this behavior. You'd have to provide more information, otherwise nobody can make an assumption what's going on.

You may also try zsync_curl's successor, [zsync2](https://github.com/TheAssassin/zsync2), which is currently under heavy development.

**Comment by probonopd** [comment]
...and set the `CURLOPT_VERBOSE` environment variable to see what is going on inside libcurl.

**Comment by TheAssassin** [comment]
@maltesh please switch to zsync2, and report bugs there if you find some. Closing as this repository is no longer developed.
