### ISSUE TITLE
Compilation on MacOS

### ISSUE THREAD

**Issue by archie3d-spitfireaudio** [probonopd/zsync-curl#35]
Compilation on MacOS requires additional `strings.h` include in `http.c`:

```c
#ifdef __APPLE__
#    include <strings.h>
#endif
```

**Comment by TheAssassin** [comment]
This project is more or less abandoned. We've got zsync2 instead, with zsync3 as a potential successor already.
If you want to, you can send a PR and I'll merge it quickly. But afterwards, I'll archive the repo.

Edit: I don't think you need the guards, including `string.h` shouldn't break anything.

**Comment by archie3d-spitfireaudio** [comment]
Sure. Sent a PR your way.

**Comment by probonopd** [comment]
Thank you  @archie3d-spitfireaudio
