### ISSUE TITLE
Git repo contains generated files

### ISSUE THREAD

**Issue by rossburton** [probonopd/zsync-curl#39]
config.guess, config.status, Makefile.in, etc should all be removed from the repository.

**Comment by probonopd** [comment]
Thanks, agree that this should be done. And it should be documented how to run the steps needed to recreate those files (which packages to install, which commands to run). I never quite understood all the auto*.

**Comment by rossburton** [comment]
The idiom is to Install autoconf and automake, then run `autoreconf --install`.  I updated the build scripts.
