### ISSUE TITLE
Dumps target file to stdout

### ISSUE THREAD

**Issue by probonopd** [probonopd/zsync-curl#6]
We are currently using range 0-0 to find out the final redirected URL of the payload file. However, if the server does not support range requests, then this fails and the full file is dumped to the command line instead.

Bintray, for example, uses Amazon CloudFront and redirects there. However, shortly after uploading a file it is not available on CloudFront yet and during that time, Bintray doesn't redirect to CloudFront.

In this case, the file is dumped to stdout, which must be prevented.

The issue is located in the source code here:
https://github.com/probonopd/zsync-curl/blob/master/src/client.c#L312-L317

**Comment by probonopd** [comment]
The following works: `curl https://dl.bintray.com/probono/AppImages/Leafpad-0.8.17-x86_64.AppImage -w '%{redirect_url}'` - TODO: check with the curl source code how this is implemented and use it.

However this does not follow multiple redirects automatically, so we must wrap this in a loop that ends once the url and the redirect url are the same.

**Comment by TheAssassin** [comment]
Please switch to [zsync2](https://github.com/TheAssassin/zsync2), and report bugs there if you find some. Closing as this repository is no longer developed.
