### ISSUE TITLE
Turn into embeddable library

### ISSUE THREAD

**Issue by probonopd** [probonopd/zsync-curl#7]
Along the lines of https://github.com/th-in-gs/zsync/commit/6e1c3de2d7ba125cda0d298c06374734d4cbc835

**Comment by TheAssassin** [comment]
Update: We are going to create a library during the rewrite the "frontend" in C++, and a small commandline application that makes use of this library.

**Comment by TheAssassin** [comment]
Please switch to [zsync2](https://github.com/TheAssassin/zsync2), and report bugs there if you find some. Closing as this repository is no longer developed.
