### ISSUE TITLE
Add switch for CURLOPT_REDIR_PROTOCOLS

### ISSUE THREAD

**Issue by probonopd** [probonopd/zsync-curl#8]
Some servers redirect to HTTPS even though HTTP was requested and even though they also support HTTP. 
If we integrate CURLOPT_REDIR_PROTOCOLS then we can get rid of the need for HTTPS dependencies (and save some server load) by enforcing plain HTTP.

http://curl.haxx.se/libcurl/c/CURLOPT_REDIR_PROTOCOLS.html

We should check CURL_VERSION_SSL and only if it indicates that HTTPS is supported it should be supported for redirects.

http://curl.haxx.se/libcurl/c/curl_version_info.html

Generally it would be useful if libcurl would only allow redirects to supported protocols and otherwise try to stay on the same protocol.

**Comment by probonopd** [comment]
Unfortunately, CURLPROTO_STAYSAME has not been added to libcurl yet, as the [TODO](http://curl.haxx.se/docs/todo.html#Refuse_downgrade_redirects) file states. > Refuse "downgrade" redirects
> 
> See https://github.com/bagder/curl/issues/226
> 
> Consider a way to tell curl to refuse to "downgrade" protocol with a redirect and/or possibly a bit that refuses redirect to change protocol completely.

**Comment by TheAssassin** [comment]
Please switch to [zsync2](https://github.com/TheAssassin/zsync2), and report bugs there if you find some. Closing as this repository is no longer developed.
