### ISSUE TITLE
Add normal HTTP download capability 

### ISSUE THREAD

**Issue by probonopd** [probonopd/zsync-curl#9]
Add normal HTTP download capability as to replace the `curl` command line tool for AppImageUpdate so that [appimageupdate](https://github.com/probonopd/AppImageKit/blob/master/AppImageUpdate.AppDir/usr/bin/appimageupdate) no longer needs `curl` in addition to `curl_zsync`.

**Comment by TheAssassin** [comment]
Please switch to [zsync2](https://github.com/TheAssassin/zsync2), and report bugs there if you find some. Closing as this repository is no longer developed.
